# Generated by Django 3.1.1 on 2020-09-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_events_tit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='datetime',
            field=models.DateField(),
        ),
    ]
